name: laboratorio1
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter_svg: ^2.0.10+1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  logger: ^2.4.0


flutter:
  fonts:
    - family: Daydream
      fonts:
        - asset: assets/fonts/Daydream.ttf

    - family: TimesNewRoman
      fonts:
        - asset: assets/fonts/times_new_roman.ttf
        - asset: assets/fonts/times_new_roman_italic.ttf
        - asset: assets/fonts/times_new_roman_bold.ttf
        - asset: assets/fonts/times_new_roman_bold_italic.ttf

  uses-material-design: true

  assets:
    - assets/icons/triforce.svg
